name: integracion continua con node.js

on:
  pull_request:
    branches: [ main ]

jobs:
  ci_to_master:
    runs-on: windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setups-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
